export default Object.freeze({
   BRANDS: {
      GOOGLE: 'mdi-google',
      APPLE: 'mdi-apple',
      FACEBOOK: 'mdi-facebook',
   },
   CONTROLS: {
      SETTINGS: 'mdi-cog',
      EDIT: 'mdi-pencil-circle',
      EXCLAIM: 'mdi-alert-circle',
      FILTER: 'mdi-filter',
      MENU: 'mdi-menu',
      CLOSE: 'mdi-close-circle',
      DELETE: 'mdi-minus-circle',
      CONFIRM: 'mdi-check-circle',
      TOMBSTONE: 'mdi-grave-stone',
      STORAGE: 'mdi-archive',
      PLUS: 'mdi-plus',
   },
   PAGES: {
      POKEMON: 'mdi-pokeball',
      GYM: 'mdi-pokemon-go',
      ROUTES: 'mdi-routes',
      RULES: 'mdi-gavel',
      LOGOUT: 'mdi-logout',
      LOGIN: 'mdi-login',
      REGISTER: 'mdi-account',
      HOME: 'mdi-home',
      GAMES: 'mdi-format-list-bulleted',
   },
   CONSOLES: {
      GAMEBOY: 'mdi-nintendo-game-boy',
      SWITCH: 'mdi-nintendo-switch',
      DESKTOP: 'mdi-monitor',
      DEFAULT: 'mdi-gamepad-square',
   },
   MISC: {
      NUZLOOKE: './img/icons/mstile-70x70.png',
      POKEBALL: './img/poke-ball.png',
   },
});
